config/routes.rb
# in routes always set the URL

# sample: use "resources :welcome" to generate url link

Rails.application.routes.draw do
  resources :stocks
  get 'welcome/index'
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  devise_scope :user do
    authenticated :user do
      namespace :users do
        get 'dashboard/index', as: :authenticated_root
        get 'dashboard/stockslist'
        get 'dashboard/transactions'
        get 'dashboard/:id/buy', to:'dashboard#buy', as: :buy
        post 'dashboard/:id/buy_transaction', to:'dashboard#buy_transaction', as: :buy_transaction
        get 'dashboard/:id/sell', to:'dashboard#sell', as: :sell
        post 'dashboard/:id/sell_transaction', to:'dashboard#sell_transaction', as: :sell_transaction
      end
    end
  end
  
  devise_scope :admin do
    authenticated :admin do
      namespace :admins do
        get 'dashboard/index', as: :authenticated_root
        patch 'dashboard/:id/update', to:'dashboard#update', as: :approved
        # used this url in admin-dashboard-index
        # create a route for patch/update
        # "as: :approved" is used to customizing your url link. check admins-dashboard-index for sample view
      end
    end
  end

  root to: 'welcome#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :transactions, dependent: :destroy
  has_many :stocks, through: :transactions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         # if role left blank, it will not accept
         validates :role, presence: true
  
  def active_for_authentication?
    super && approved?
  end
  # super inherits ApplicationRecord && approved

  def inactive_message 
    approved? ? super : :not_approved
  end
  
end

app/controllers/admins/dashboard_controller.rb
class Admins::DashboardController < ApplicationController
  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    @user.update(:approved=>true)

    redirect_to admins_authenticated_root_path(@user), notice: "user was successfully approved."
    # finding the user/id and updating it to boolean value" true
  end

end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  # use @ to use it within the class

  def index
    # pulling of API data
    client = Stock.iex

    # query the database then update the stock prices
    Stock.all.each do |stock|
      stock.update!(price: client.quote(stock.name).latest_price)
    end

    @stocks = Stock.all

    # # looping through the transactions and getting the needed data in index
    # @transactions = current_user.transactions.all

    # getting the sum of the current user's per stock quantity
    @msft_stocks_owned = get_sum(current_user, Stock.find(1))
    @fb_stocks_owned = get_sum(current_user, Stock.find(2))
    @twtr_stocks_owned = get_sum(current_user, Stock.find(3))
  end

  def stockslist
    # pulling of API data
    client = Stock.iex

    # query the database then update the stock prices
    Stock.all.each do |stock|
      stock.update!(price: client.quote(stock.name).latest_price)
    end

    @stocks = Stock.all

    @msft_stocks_owned = get_sum(current_user, Stock.find(1))
    @fb_stocks_owned = get_sum(current_user, Stock.find(2))
    @twtr_stocks_owned = get_sum(current_user, Stock.find(3))
  end

  def transactions
    @transactions = current_user.transactions.all
    
    @msft_stocks_owned = get_sum(current_user, Stock.find(1))
    @fb_stocks_owned = get_sum(current_user, Stock.find(2))
    @twtr_stocks_owned = get_sum(current_user, Stock.find(3))
  end

  def new
    @transaction = Transaction.new
  end

  def buy
    # used for views
    @stock = Stock.find(params[:id])
  end

  def buy_transaction
    # method in form
    @stock = Stock.find(params[:id])

    # for transaction history tracking
    Transaction.create(
      user_id: current_user.id,
      stock_id: params[:id],
      stock_name: @stock.name,
      buy: true,
      sell: false,
      price: @stock.price,
      quantity: params[:buy_transaction][:quantity]
      # [:name of form],[:field quantity]
      # name of the form and what value you are getting
    )
    
    # basic math of deducting quantity from stock model and adding quantity for user model
    @transaction = current_user.transactions.last.quantity
    @user = current_user
    @user.credit -= (@stock.price * @transaction)
    @user.save!

    # update stock quantity
    @stock.quantity -= @transaction
    @stock.save!

    # same as redirect_to "/users/dashboard/index"
    redirect_to users_authenticated_root_path
  end

  def sell
    @stock = Stock.find(params[:id])
  end

  def sell_transaction
    @user = current_user
    @stock = Stock.find(params[:id])

    Transaction.create(
      user_id: current_user.id,
      stock_id: params[:id],
      stock_name: @stock.name,
      buy: false,
      sell: true,
      price: @stock.price,
      quantity: params[:sell_transaction][:quantity]
    )
    
    @sell_quantity = params[:sell_transaction][:quantity].to_f

    # add user credit
    @user.credit += (@stock.price * @sell_quantity)
    @user.save!

    # add stock quantity
    @stock.quantity += @sell_quantity
    @stock.save!

    redirect_to users_authenticated_root_path
  end

  private
  def transaction_params
    params.require(:transaction).permit(:quantity)
  end

  # processing the .sum(:quantity) of buy:true & sell:true
  def get_sum(current_user, stock)
    current_stock_sum = Transaction.where(user_id: current_user.id, stock_id: stock.id, buy: true).sum(:quantity)
    current_stock_diff = Transaction.where(user_id: current_user.id, stock_id: stock.id, sell: true).sum(:quantity)
    current_stock_sum -= current_stock_diff
   
    current_stock_sum
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  include Accessible
  skip_before_action :check_resource, except: [:new, :create]

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.mailer_created.deliver_later
      redirect_to root_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :role, :password, :password_confirmation)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_resource, only: :destroy
end

app/helpers/admins/dashboard_helper.rb
module Admins::DashboardHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/views/users/dashboard/buy.html.erb
<div class="bg-white py-16 sm:py-24">
  <div class="relative sm:py-16">
    <div aria-hidden="true" class="hidden sm:block">
      <div class="absolute inset-y-0 left-0 w-1/2 bg-gray-50 rounded-r-3xl"></div>
      <svg class="absolute top-8 left-1/2 -ml-3" width="404" height="392" fill="none" viewBox="0 0 404 392">
        <defs>
          <pattern id="8228f071-bcee-4ec8-905a-2a059a2cc4fb" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
            <rect x="0" y="0" width="4" height="4" class="text-gray-200" fill="currentColor" />
          </pattern>
        </defs>
        <rect width="404" height="392" fill="url(#8228f071-bcee-4ec8-905a-2a059a2cc4fb)" />
      </svg>
    </div>
    <div class="mx-auto max-w-md px-4 sm:max-w-3xl sm:px-6 lg:max-w-7xl lg:px-8">
      <div class="relative rounded-2xl px-6 py-10 bg-indigo-600 overflow-hidden shadow-xl sm:px-12 sm:py-20">
        <div aria-hidden="true" class="absolute inset-0 -mt-72 sm:-mt-32 md:mt-0">
          <svg class="absolute inset-0 h-full w-full" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 1463 360">
            <path class="text-indigo-500 text-opacity-40" fill="currentColor" d="M-82.673 72l1761.849 472.086-134.327 501.315-1761.85-472.086z" />
            <path class="text-indigo-700 text-opacity-40" fill="currentColor" d="M-217.088 544.086L1544.761 72l134.327 501.316-1761.849 472.086z" />
          </svg>
        </div>
        <div class="relative">
          <div class="sm:text-center">
            <h2 class="text-3xl font-extrabold text-white tracking-tight sm:text-4xl">
              Buy <%= @stock.name %> Stocks.
            </h2>
            <p class="mt-6 mx-auto max-w-2xl text-lg text-indigo-200">
              Quantity
            </p>
            <br>
          </div>
          <%= form_for("buy_transaction", url: "/users/dashboard/#{params[:id]}/buy_transaction", method: "post") do |f| %>
          <form action="#" class="mt-12 sm:mx-auto sm:max-w-lg sm:flex">
            <div class="min-w-0 flex-1">
              <%= f.label :quantity, class:"sr-only" %>
              <%= f.number_field :quantity, class:"block w-full border border-transparent rounded-md px-5 py-3 text-base text-gray-900 placeholder-gray-500 shadow-sm focus:outline-none focus:border-transparent focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-indigo-600" %>
            </div>
            <Span class="mt-4 sm:mt-0 sm:ml-3">
              <%= f.submit "Save Buy Transaction", class:"block w-full rounded-md border border-transparent px-5 py-3 bg-indigo-500 text-base font-medium text-white shadow hover:bg-indigo-400 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-indigo-600 sm:px-10" %>
            </span>
          </form>
          <% end %>
          <Span class="mt-4 sm:mt-0 sm:ml-3"> 
          <%= link_to 'Go Back', users_dashboard_stockslist_path, class:"text-center block w-full rounded-md border border-transparent px-5 py-3 text-base font-medium text-white hover:text-indigo-400 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-indigo-600 sm:px-10" %>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/dashboard/index.html.erb
<h1>Users::Dashboard#index</h1>
<p>Find me in app/views/users/dashboard/index.html.erb</p>

<h2>User: <%= current_user.email %></h2>
<h2>Credit: <%= current_user.credit %></h2>

<h1>Stocks Owned</h1>
MSFT: <%= @msft_stocks_owned %>
<br>
FB: <%= @fb_stocks_owned %>
<br>
TWRT: <%= @twtr_stocks_owned %>

<h1>Stock List</h1>
<table>
  <th>
    <tr>
      <td>Name</td>
      <td>Price</td>
      <td>Quantity</td>
      <td></td>
      <td></td>
    </tr>
  </th>
  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.price %></td>
        <td><%= stock.quantity %></td>
        <td><%= link_to 'Buy', users_buy_path(stock) %></td>
        <td><%= link_to 'Sell', users_sell_path(stock) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Transaction History</h1>
<table>
  <th>
    <tr>
      <td>Stock Name</td>
      <td>Stock Price</td>
      <td>Quantity</td>
      <td>Status</td>
    </tr>
  </th>
  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.stock_name %></td>
        <td><%= transaction.price %></td>
        <td><%= transaction.quantity %></td>
        <td><% if transaction.buy == true %>
              Bought
            <% else %>
              Sold
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/dashboard/sell.html.erb
<div class="bg-white py-16 sm:py-24">
  <div class="relative sm:py-16">
    <div aria-hidden="true" class="hidden sm:block">
      <div class="absolute inset-y-0 left-0 w-1/2 bg-gray-50 rounded-r-3xl"></div>
      <svg class="absolute top-8 left-1/2 -ml-3" width="404" height="392" fill="none" viewBox="0 0 404 392">
        <defs>
          <pattern id="8228f071-bcee-4ec8-905a-2a059a2cc4fb" x="0" y="0" width="20" height="20" patternUnits="userSpaceOnUse">
            <rect x="0" y="0" width="4" height="4" class="text-gray-200" fill="currentColor" />
          </pattern>
        </defs>
        <rect width="404" height="392" fill="url(#8228f071-bcee-4ec8-905a-2a059a2cc4fb)" />
      </svg>
    </div>
    <div class="mx-auto max-w-md px-4 sm:max-w-3xl sm:px-6 lg:max-w-7xl lg:px-8">
      <div class="relative rounded-2xl px-6 py-10 bg-indigo-600 overflow-hidden shadow-xl sm:px-12 sm:py-20">
        <div aria-hidden="true" class="absolute inset-0 -mt-72 sm:-mt-32 md:mt-0">
          <svg class="absolute inset-0 h-full w-full" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 1463 360">
            <path class="text-indigo-500 text-opacity-40" fill="currentColor" d="M-82.673 72l1761.849 472.086-134.327 501.315-1761.85-472.086z" />
            <path class="text-indigo-700 text-opacity-40" fill="currentColor" d="M-217.088 544.086L1544.761 72l134.327 501.316-1761.849 472.086z" />
          </svg>
        </div>
        <div class="relative">
          <div class="sm:text-center">
            <h2 class="text-3xl font-extrabold text-white tracking-tight sm:text-4xl">
              Sell <%= @stock.name %> Stocks.
            </h2>
            <p class="mt-6 mx-auto max-w-2xl text-lg text-indigo-200">
              Quantity
            </p>
            <br>
          </div>
          <%= form_for("sell_transaction", url: "/users/dashboard/#{params[:id]}/sell_transaction", method: "post") do |f| %>
          <form action="#" class="mt-12 sm:mx-auto sm:max-w-lg sm:flex">
            <div class="min-w-0 flex-1">
              <%= f.label :quantity, class:"sr-only" %>
              <%= f.number_field :quantity, class:"block w-full border border-transparent rounded-md px-5 py-3 text-base text-gray-900 placeholder-gray-500 shadow-sm focus:outline-none focus:border-transparent focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-indigo-600" %>
            </div>
            <Span class="mt-4 sm:mt-0 sm:ml-3">
              <%= f.submit "Save Sell Transaction", class:"block w-full rounded-md border border-transparent px-5 py-3 bg-indigo-500 text-base font-medium text-white shadow hover:bg-indigo-400 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-indigo-600 sm:px-10" %>
            </span>
          </form>
          <% end %>
          <Span class="mt-4 sm:mt-0 sm:ml-3">
          <%= link_to 'Go Back', users_dashboard_stockslist_path, class:"text-center block w-full rounded-md border border-transparent px-5 py-3 text-base font-medium text-white hover:text-indigo-400 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-indigo-600 sm:px-10" %>
        </span>
        </div>
      </div>
    </div>
  </div>
</div>