config/routes.rb
# in routes always set the URL

# sample: use "resources :welcome" to generate url link

Rails.application.routes.draw do
  resources :stocks
  get 'welcome/index'
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  devise_scope :user do
    authenticated :user do
      namespace :users do
        get 'dashboard/index', as: :authenticated_root
        get 'dashboard/stockslist'
        get 'dashboard/transactions'
        get 'dashboard/:id/buy', to:'dashboard#buy', as: :buy
        post 'dashboard/:id/buy_transaction', to:'dashboard#buy_transaction', as: :buy_transaction
        get 'dashboard/:id/sell', to:'dashboard#sell', as: :sell
        post 'dashboard/:id/sell_transaction', to:'dashboard#sell_transaction', as: :sell_transaction
      end
    end
  end
  
  devise_scope :admin do
    authenticated :admin do
      namespace :admins do
        get 'dashboard/index', as: :authenticated_root
        patch 'dashboard/:id/update', to:'dashboard#update', as: :approved
        # used this url in admin-dashboard-index
        # create a route for patch/update
        # "as: :approved" is used to customizing your url link. check admins-dashboard-index for sample view
      end
    end
  end

  root to: 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container">
<div class="min-h-screen">
  <div class="relative overflow-hidden">
    <header class="relative">
      <div class="bg-gray-900 pt-6">
        <nav class="relative max-w-7xl mx-auto flex items-center justify-between px-4 sm:px-6" aria-label="Global">
        <div class="flex items-center justify-between w-full md:w-auto">
        <a href="#">
          <span class="sr-only">Workflow</span>
          <img class="h-16 w-auto sm:h-18" src="/strad.png" alt="">
        </a>
        </div>
        <% if user_signed_in? %>
        <div class="hidden md:flex md:items-center md:space-x-6" >
              <p class="forFonts"><%= link_to 'Dashboard', users_authenticated_root_path %></p>
              <p class="forFonts"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></p>
          <% elsif admin_signed_in? %>
            <p class="forFonts"><%= link_to 'Dashboard', admins_authenticated_root_path %></p>
            <p class="forFonts"><%= link_to 'Log Out', destroy_admin_session_path, method: :delete %></p>
          <% else %>
              <p class="forFonts"><%= link_to "Log In as User", new_user_session_path %></p>
              <p class="forFonts"><%= link_to "Log In as Admin", new_admin_session_path %></p>
         <% end %>
        </div>
        </nav>
      </div>
    </header>

    <main>
      <div class="pt-10 bg-gray-900 sm:pt-16 lg:pt-8 lg:pb-14 lg:overflow-hidden">
        <div class="mx-auto max-w-7xl lg:px-8">
          <div class="lg:grid lg:grid-cols-2 lg:gap-8">
            <div class="mx-auto max-w-md px-4 sm:max-w-2xl sm:px-6 sm:text-center lg:px-0 lg:text-left lg:flex lg:items-center">
              <div class="lg:py-24">
                <h1 class="mt-4 text-4xl tracking-tight font-extrabold text-white sm:mt-5 sm:text-6xl lg:mt-6 xl:text-6xl">
                  <span class="block">Start your stock trading journey</span>
                  <span class="block text-indigo-400">with us!</span>
                </h1>
                <p class="mt-3 text-base text-gray-300 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl">
                Investing has never been easier. Everything you are looking for in an ultimate investment platform — on the device of your choice.                </p>
                <div class="mt-10 sm:mt-12">
                  <form action="#" class="sm:max-w-xl sm:mx-auto lg:mx-0">
                    <div class="sm:flex">
                      <div class="mt-3 sm:mt-0 sm:ml-3">
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <div class="mt-12 -mb-16 sm:-mb-48 lg:m-0 lg:relative">
              <div class="mx-auto max-w-md px-4 sm:max-w-2xl sm:px-6 lg:max-w-none lg:px-0">
                <!-- Illustration taken from Lucid Illustrations: https://lucid.pixsellz.io/ -->
                <img class="w-full lg:absolute lg:inset-y-0 lg:left-0 lg:h-full lg:w-auto lg:max-w-none" src="https://tailwindui.com/img/component-images/cloud-illustration-indigo-400.svg" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>
</div>