config/routes.rb
# in routes always set the URL

# sample: use "resources :welcome" to generate url link

Rails.application.routes.draw do
  resources :stocks
  get 'welcome/index'
  devise_for :users, path: 'users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  devise_scope :user do
    authenticated :user do
      namespace :users do
        get 'dashboard/index', as: :authenticated_root
        get 'dashboard/stockslist'
        get 'dashboard/transactions'
        get 'dashboard/:id/buy', to:'dashboard#buy', as: :buy
        post 'dashboard/:id/buy_transaction', to:'dashboard#buy_transaction', as: :buy_transaction
        get 'dashboard/:id/sell', to:'dashboard#sell', as: :sell
        post 'dashboard/:id/sell_transaction', to:'dashboard#sell_transaction', as: :sell_transaction
      end
    end
  end
  
  devise_scope :admin do
    authenticated :admin do
      namespace :admins do
        get 'dashboard/index', as: :authenticated_root
        patch 'dashboard/:id/update', to:'dashboard#update', as: :approved
        # used this url in admin-dashboard-index
        # create a route for patch/update
        # "as: :approved" is used to customizing your url link. check admins-dashboard-index for sample view
      end
    end
  end

  root to: 'welcome#index'
end

app/controllers/admins/dashboard_controller.rb
class Admins::DashboardController < ApplicationController
  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    @user.update(:approved=>true)

    redirect_to admins_authenticated_root_path(@user), notice: "user was successfully approved."
    # finding the user/id and updating it to boolean value" true
  end

end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  # use @ to use it within the class

  def index
    # pulling of API data
    client = Stock.iex

    # query the database then update the stock prices
    Stock.all.each do |stock|
      stock.update!(price: client.quote(stock.name).latest_price)
    end

    @stocks = Stock.all

    # # looping through the transactions and getting the needed data in index
    # @transactions = current_user.transactions.all

    # getting the sum of the current user's per stock quantity
    @msft_stocks_owned = get_sum(current_user, Stock.find(1))
    @fb_stocks_owned = get_sum(current_user, Stock.find(2))
    @twtr_stocks_owned = get_sum(current_user, Stock.find(3))
  end

  def stockslist
    # pulling of API data
    client = Stock.iex

    # query the database then update the stock prices
    Stock.all.each do |stock|
      stock.update!(price: client.quote(stock.name).latest_price)
    end

    @stocks = Stock.all

    @msft_stocks_owned = get_sum(current_user, Stock.find(1))
    @fb_stocks_owned = get_sum(current_user, Stock.find(2))
    @twtr_stocks_owned = get_sum(current_user, Stock.find(3))
  end

  def transactions
    @transactions = current_user.transactions.all
    
    @msft_stocks_owned = get_sum(current_user, Stock.find(1))
    @fb_stocks_owned = get_sum(current_user, Stock.find(2))
    @twtr_stocks_owned = get_sum(current_user, Stock.find(3))
  end

  def new
    @transaction = Transaction.new
  end

  def buy
    # used for views
    @stock = Stock.find(params[:id])
  end

  def buy_transaction
    # method in form
    @stock = Stock.find(params[:id])

    # for transaction history tracking
    Transaction.create(
      user_id: current_user.id,
      stock_id: params[:id],
      stock_name: @stock.name,
      buy: true,
      sell: false,
      price: @stock.price,
      quantity: params[:buy_transaction][:quantity]
      # [:name of form],[:field quantity]
      # name of the form and what value you are getting
    )
    
    # basic math of deducting quantity from stock model and adding quantity for user model
    @transaction = current_user.transactions.last.quantity
    @user = current_user
    @user.credit -= (@stock.price * @transaction)
    @user.save!

    # update stock quantity
    @stock.quantity -= @transaction
    @stock.save!

    # same as redirect_to "/users/dashboard/index"
    redirect_to users_authenticated_root_path
  end

  def sell
    @stock = Stock.find(params[:id])
  end

  def sell_transaction
    @user = current_user
    @stock = Stock.find(params[:id])

    Transaction.create(
      user_id: current_user.id,
      stock_id: params[:id],
      stock_name: @stock.name,
      buy: false,
      sell: true,
      price: @stock.price,
      quantity: params[:sell_transaction][:quantity]
    )
    
    @sell_quantity = params[:sell_transaction][:quantity].to_f

    # add user credit
    @user.credit += (@stock.price * @sell_quantity)
    @user.save!

    # add stock quantity
    @stock.quantity += @sell_quantity
    @stock.save!

    redirect_to users_authenticated_root_path
  end

  private
  def transaction_params
    params.require(:transaction).permit(:quantity)
  end

  # processing the .sum(:quantity) of buy:true & sell:true
  def get_sum(current_user, stock)
    current_stock_sum = Transaction.where(user_id: current_user.id, stock_id: stock.id, buy: true).sum(:quantity)
    current_stock_diff = Transaction.where(user_id: current_user.id, stock_id: stock.id, sell: true).sum(:quantity)
    current_stock_sum -= current_stock_diff
   
    current_stock_sum
  end
end

app/helpers/admins/dashboard_helper.rb
module Admins::DashboardHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/views/admins/dashboard/index.html.erb
<div class="container">
<h1 class="adminDashboard">ADMIN DASHBOARD</h1>
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr class="bg-indigo-500" >
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider">
                USERS
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider">
                EMAIL
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider">
                ROLE
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider">
                CREDIT
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider">
                STATUS
              </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-white uppercase tracking-wider">
                Approval
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
          <% @users.each do |user| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="flex items-center">
                  <div class="flex-shrink-0 h-10 w-10">
                    <img class="h-10 w-10 rounded-full" src="/user.png" alt="">
                  </div>
                  
                  <div class="ml-4">
                    <div class="text-sm font-medium text-gray-900">
                      Account Number: <%= user.id %>
                    </div>
                    <div class="text-sm text-gray-500">
                      <%= user.email %>
                    </div>
                  </div>
                </div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <%= user.email %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <% if user.role == "Broker" %>
                  <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-600 text-gray-200">
                    <%= user.role %>
                  </span>
                <% else %>
                  <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-400 text-gray-100">
                    <%= user.role %>
                  </span>
                <% end %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                <%= user.credit %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                <% if user.approved == true %>
                <span class="text-green-500">Activated</span>
                <% else %>
                <span class="text-red-500">Pending</span>
              <% end %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-bold text-indigo-500">
                <%= link_to "Confirm", admins_approved_path(user), method: :patch %>
              </td>
            </tr>
            <% end %>
            <!-- More people... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="goBack">
<p class="gobacktext"><%= link_to "Go back", welcome_index_path %> 
</p>
</div>
</div>